### ISSUE TITLE
AIService服务注入失败

### ISSUE THREAD

**Issue by StevenYounng** [LnYo-Cly/ai4j#26]
Spring boot 项目，使用提供的测试代码，AiService注入失败，无论是Autowired或Resource都无法正常注入。
java版本：1.8，SpringBoot：2.7
报错信息：
***************************
APPLICATION FAILED TO START
***************************

Description:

Field aiService in com.ysc.springbootinit.controller.OpenAiController required a bean of type 'io.github.lnyocly.ai4j.service.factor.AiService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'io.github.lnyocly.ai4j.service.factor.AiService' in your configuration.

Process finished with exit code 1

![image](https://github.com/user-attachments/assets/317930cb-c0fc-48ee-904b-acc8052aba65)

**Comment by LnYo-Cly** [comment]
你可以引入当前最新版本的坐标进行尝试：
```xml
<dependency>
    <groupId>io.github.lnyo-cly</groupId>
    <artifactId>ai4j-spring-boot-starter</artifactId>
    <version>0.7.2</version>
</dependency>
```
并在idea的maven管理处，先手动进行`clean`，再进行`reload`刷新，确保成功引入。
如果依旧报错，请您再次反馈，感谢。

**Comment by StevenYounng** [comment]
感谢！已解决
